###
GET http://127.0.0.1:8000/api/teams
Accept: application/json

###
GET http://127.0.0.1:8000/api/teams/1
Accept: application/json

###
GET http://127.0.0.1:8000/api/teams/1/members

###
POST http://127.0.0.1:8000/api/teams
Content-Type: application/json

{
  "name": "newTeam"
}

###
PUT http://127.0.0.1:8000/api/teams/26
Content-Type: application/json

{
  "name": "newTeam2"
}

###
DELETE http://127.0.0.1:8000/api/teams/26
Content-Type: application/json


